export const DELIVERY_CREATE_REQUEST = "DELIVERY_CREATE_REQUEST";
export const DELIVERY_CREATE_SUCCESS = "DELIVERY_CREATE_SUCCESS";
export const DELIVERY_CREATE_FAIL = "DELIVERY_CREATE_FAIL";

export const DELIVERY_GET_REQUEST = "DELIVERY_GET_REQUEST";
export const DELIVERY_GET_SUCCESS = "DELIVERY_GET_SUCCESS";
export const DELIVERY_GET_FAIL = "DELIVERY_GET_FAIL";

export const DELIVERY_SINGLE_REQUEST = "DELIVERY_SINGLE_REQUEST";
export const DELIVERY_SINGLE_SUCCESS = "DELIVERY_SINGLE_SUCCESS";
export const DELIVERY_SINGLE_FAIL = "DELIVERY_SINGLE_FAIL";
