export const COMPANY_CREATE_REQUEST = "COMPANY_CREATE_REQUEST";
export const COMPANY_CREATE_SUCCESS = "COMPANY_CREATE_SUCCESS";
export const COMPANY_CREATE_FAIL = "COMPANY_CREATE_FAIL";

export const COMPANY_GET_REQUEST = "COMPANY_GET_REQUEST";
export const COMPANY_GET_SUCCESS = "COMPANY_GET_SUCCESS";
export const COMPANY_GET_FAIL = "COMPANY_GET_FAIL";

export const COMPANY_SINGLE_REQUEST = "COMPANY_SINGLE_REQUEST";
export const COMPANY_SINGLE_SUCCESS = "COMPANY_SINGLE_SUCCESS";
export const COMPANY_SINGLE_FAIL = "COMPANY_SINGLE_FAIL";
