export const TRACKING_ACCEPT_REQUEST = 'TRACKING_ACCEPT_REQUEST';
export const TRACKING_ACCEPT_SUCCESS = 'TRACKING_ACCEPT_SUCCESS';
export const TRACKING_ACCEPT_FAIL = 'TRACKING_ACCEPT_FAIL';

export const TRACKING_CHECKPOINT_REQUEST = 'TRACKING_CHECKPOINT_REQUEST';
export const TRACKING_CHECKPOINT_SUCCESS = 'TRACKING_CHECKPOINT_SUCCESS';
export const TRACKING_CHECKPOINT_FAIL = 'TRACKING_CHECKPOINT_FAIL';

export const TRACKING_SINGLE_REQUEST = 'TRACKING_SINGLE_REQUEST';
export const TRACKING_SINGLE_SUCCESS = 'TRACKING_SINGLE_SUCCESS';
export const TRACKING_SINGLE_FAIL = 'TRACKING_SINGLE_FAIL';

export const TRACKING_GET_REQUEST = 'TRACKING_GET_REQUEST';
export const TRACKING_GET_SUCCESS = 'TRACKING_GET_SUCCESS';
export const TRACKING_GET_FAIL = 'TRACKING_GET_FAIL';

export const HIDE_COMPLETED = 'HIDE_COMPLETED';

export const TRACKING_AVAILABLE_RESCHEDULE_REQUEST =
  'TRACKING_AVAILABLE_RESCHEDULE_REQUEST';
export const TRACKING_AVAILABLE_RESCHEDULE_SUCCESS =
  'TRACKING_AVAILABLE_RESCHEDULE_SUCCESS';
export const TRACKING_AVAILABLE_RESCHEDULE_FAIL =
  'TRACKING_AVAILABLE_RESCHEDULE_FAIL';
